// Generated by CoffeeScript 1.10.0
var cb, ccb, mainBar, opcb, twDefStr, vcb, wcb;

new TwNewBar('Authority');

twDefStr = ' Authority label=\'Authority\' movable=true resizable=true color=\'%i %i %i\' position=\'%i %i\' alpha=%i text=light size=\'%i %i\' valueswidth=160 alwaystop=true';

TwDefine(twDefStr);

mainBar = new MainBar;

opcb = new OnlinePlayers(MainBar);

cb = new Player(MainBar);

ccb = new Clothing(MainBar);

wcb = new Weapon(MainBar);

vcb = new Vehicle(MainBar);

TwAddVarCB(mainBar, 'Index', 'TW_TYPE_INT32', OnlinePlayers.getter('SetCurrentOPlayerCallback'), OnlinePlayers.setter('GetCurrentOPlayerCallback'), opcb, ' min=0 max=30 group=OnlinePlayers');

TwAddVarCB(mainBar, 'Name', 'TW_TYPE_STDSTRING', OnlinePlayers.getter('SetMyStdStringCB'), OnlinePlayers.setter('GetMyStdStringCB'), opcb, 'group=OnlinePlayers');

TwAddButton(mainBar, 'Refresh List', OnlinePlayers.item('TRefreshList'), NULL, 'group=OnlinePlayers ');

TwAddButton(mainBar, 'Give Player Weapons', OnlinePlayers.item('TPlayer0'), NULL, 'group=OnlinePlayers ');

TwAddButton(mainBar, 'Teleport to Player', OnlinePlayers.item('TTPPlayer0'), NULL, 'group=OnlinePlayers ');

TwSetParam(mainBar, 'Online', 'opened', 'TW_PARAM_INT32', 1, 'player_opened');

TwAddVarRW(mainBar, 'Invincibility', 'TW_TYPE_BOOLCPP', Player.item('godmode'), 'group=Player');

TwAddVarRW(mainBar, 'Off The Radar', 'TW_TYPE_BOOLCPP', Player.item('offradar'), 'group=Player');

TwAddVarRW(mainBar, 'No Ragdoll', 'TW_TYPE_BOOLCPP', Player.item('noragdoll'), 'group=Player');

TwAddVarRW(mainBar, 'Invisible', 'TW_TYPE_BOOLCPP', Player.item('invisible'), 'group=Player');

TwAddVarRW(mainBar, 'Super Jump', 'TW_TYPE_BOOLCPP', Player.item('superjump'), 'group=Player');

TwAddVarRW(mainBar, 'Never Wanted', 'TW_TYPE_BOOLCPP', Player.item('neverwanted'), 'group=Player');

TwAddVarRW(mainBar, 'RP Loop', 'TW_TYPE_BOOLCPP', Player.item('rp'), 'group=Player');

TwAddVarRW(mainBar, 'No Player Gravity', 'TW_TYPE_BOOLCPP', Player.item('nogravity'), 'group=Player');

TwAddVarRW(mainBar, 'Tiny Player', 'TW_TYPE_BOOLCPP', Player.item('tinyplayer'), 'group=Player');

TwAddSeparator(mainBar, NULL, ' group=\'Player\' ');

TwAddVarCB(mainBar, 'Health', 'TW_TYPE_FLOAT', Player.getter('SetHealthCallback'), Player.setter('GetHealthCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Max Health', 'TW_TYPE_FLOAT', Player.getter('SetMaxHealthCallback'), Player.setter('GetMaxHealthCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Armor', 'TW_TYPE_FLOAT', Player.getter('SetArmorCallback'), Player.setter('GetArmorCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Stamina', 'TW_TYPE_FLOAT', Player.getter('SetStaminaCallback'), Player.setter('GetStaminaCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Max Stamina', 'TW_TYPE_FLOAT', Player.getter('SetMaxStaminaCallback'), Player.setter('GetMaxStaminaCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Z Coord', 'TW_TYPE_FLOAT', Player.getter('SetZCoordCallback'), Player.setter('GetZCoordCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Move Speed', 'TW_TYPE_FLOAT', Player.getter('SetSpeedCallback'), Player.setter('GetSpeedCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Swim Speed', 'TW_TYPE_FLOAT', Player.getter('SetSwimSpeedCallback'), Player.setter('GetSwimSpeedCallback'), cb, 'group=Player');

TwAddVarCB(mainBar, 'Damage Taken', 'TW_TYPE_FLOAT', Player.getter('SetDamageTakenCallback'), Player.setter('GetDamageTakenCallback'), cb, 'group=Player');

TwSetParam(mainBar, 'Player', 'opened', 'TW_PARAM_INT32', 1, 'player_opened');

TwAddButton(mainBar, 'Cop Oufit', Clothing.item('TCopOutFit'), NULL, 'group=Clothing ');

TwAddButton(mainBar, 'Female Cop Oufit', Clothing.item('TFCopOutFit'), NULL, 'group=Clothing ');

TwAddButton(mainBar, 'Santa Oufit', Clothing.item('TSantaOutFit'), NULL, 'group=Clothing ');

TwAddButton(mainBar, 'Female Santa Oufit', Clothing.item('TFSantaOutFit'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Hat', 'TW_TYPE_INT32', Clothing.getter('SetHatCallback'), Clothing.setter('GetHatCallback'), ccb, ' min=0 max=55 group=Clothing');

TwAddVarCB(mainBar, 'Hat Texture', 'TW_TYPE_INT32', Clothing.getter('SetHatExCallback'), Clothing.setter('GetHatExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Hat', Clothing.item('THats'), NULL, 'group=Clothing');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Glasses', 'TW_TYPE_INT32', Clothing.getter('SetGlassCallback'), Clothing.setter('GetGlassCallback'), ccb, ' min=0 max=23 group=Clothing');

TwAddVarCB(mainBar, 'Glasses Texture', 'TW_TYPE_INT32', Clothing.getter('SetGlassExCallback'), Clothing.setter('GetGlassExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Glasses', Clothing.item('TGlass'), NULL, 'group=Clothing');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Earrings/Headpiece', 'TW_TYPE_INT32', Clothing.getter('SetEarCallback'), Clothing.setter('GetEarCallback'), ccb, ' min=0 max=3 group=Clothing');

TwAddVarCB(mainBar, 'Earrings/Headpiece Texture', 'TW_TYPE_INT32', Clothing.getter('SetEarExCallback'), Clothing.setter('GetEarExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Earrings/Headpiece', Clothing.item('TEars'), NULL, 'group=Clothing');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Face', 'TW_TYPE_INT32', Clothing.getter('SetFaceCallback'), Clothing.setter('GetFaceCallback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Face Texture', 'TW_TYPE_INT32', Clothing.getter('SetFaceExCallback'), Clothing.setter('GetFaceExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Face', Clothing.item('TFace'), NULL, 'group=Clothing');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Mask', 'TW_TYPE_INT32', Clothing.getter('SetMaskCallback'), Clothing.setter('GetMaskCallback'), ccb, ' min=0 max=55 group=Clothing');

TwAddVarCB(mainBar, 'Mask Texture', 'TW_TYPE_INT32', Clothing.getter('SetMaskExCallback'), Clothing.setter('GetMaskExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Mask', Clothing.item('TMask'), NULL, 'group=Clothing');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Hair', 'TW_TYPE_INT32', Clothing.getter('SetHairCallback'), Clothing.setter('GetHairCallback'), ccb, ' min=0 max=55 group=Clothing');

TwAddVarCB(mainBar, 'Hair Texture', 'TW_TYPE_INT32', Clothing.getter('SetHairExCallback'), Clothing.setter('GetHairExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Hair', Clothing.item('THair'), NULL, 'group=Clothing');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Torso', 'TW_TYPE_INT32', Clothing.getter('SetTorsoCallback'), Clothing.setter('GetTorsoCallback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Torso Texture', 'TW_TYPE_INT32', Clothing.getter('SetTorsoExCallback'), Clothing.setter('GetTorsoExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Torso', Clothing.item('THats'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Pants', 'TW_TYPE_INT32', Clothing.getter('SetLegsCallback'), Clothing.setter('GetLegsCallback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Pants Texture', 'TW_TYPE_INT32', Clothing.getter('SetLegsExCallback'), Clothing.setter('GetLegsExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Pants', Clothing.item('TLegs'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Hands', 'TW_TYPE_INT32', Clothing.getter('SetHandsCallback'), Clothing.setter('GetHandsCallback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Hands Texture', 'TW_TYPE_INT32', Clothing.getter('SetHandsExCallback'), Clothing.setter('GetHandsExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set 5', Clothing.item('THands'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Shoes', 'TW_TYPE_INT32', Clothing.getter('SetTextureCallback'), Clothing.setter('GetTextureCallback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Shoes Texture', 'TW_TYPE_INT32', Clothing.getter('SetTextureExCallback'), Clothing.setter('GetTextureExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Shoes', Clothing.item('TTexture'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Neck', 'TW_TYPE_INT32', Clothing.getter('SetShoesCallback'), Clothing.setter('GetShoesCallback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Neck Texture', 'TW_TYPE_INT32', Clothing.getter('SetShoesExCallback'), Clothing.setter('GetShoesExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Neck', Clothing.item('TShoes'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Shirt', 'TW_TYPE_INT32', Clothing.getter('SetSpecial1Callback'), Clothing.setter('GetSpecial1Callback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Shirt Texture', 'TW_TYPE_INT32', Clothing.getter('SetSpecial1ExCallback'), Clothing.setter('GetSpecial1ExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Shirt', Clothing.item('TSpecial1'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Armor', 'TW_TYPE_INT32', Clothing.getter('SetSpecial2Callback'), Clothing.setter('GetSpecial2Callback'), ccb, ' min=0 max=50 group=Clothing');

TwAddVarCB(mainBar, 'Armor Texture', 'TW_TYPE_INT32', Clothing.getter('SetSpecial2ExCallback'), Clothing.setter('GetSpecial2ExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Armor', Clothing.item('TSpecial2'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Emblem', 'TW_TYPE_INT32', Clothing.getter('SetSpecial3Callback'), Clothing.setter('GetSpecial3Callback'), ccb, ' min=0 max=100 group=Clothing');

TwAddVarCB(mainBar, 'Emblem Texture', 'TW_TYPE_INT32', Clothing.getter('SetSpecial3ExCallback'), Clothing.setter('GetSpecial3ExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Emblem', Clothing.item('TSpecial3'), NULL, 'group=Clothing ');

TwAddSeparator(mainBar, NULL, ' group=\'Clothing\' ');

TwAddVarCB(mainBar, 'Jacket', 'TW_TYPE_INT32', Clothing.getter('SetTorso2Callback'), Clothing.setter('GetTorso2Callback'), ccb, ' min=0 max=100 group=Clothing');

TwAddVarCB(mainBar, 'Jacket Texture', 'TW_TYPE_INT32', Clothing.getter('SetTorso2ExCallback'), Clothing.setter('GetTorso2ExCallback'), ccb, ' min=0 max=10 group=Clothing');

TwAddButton(mainBar, 'Set Jacket', Clothing.item('TTorso2'), NULL, 'group=Clothing ');

TwSetParam(mainBar, 'Clothing', 'opened', 'TW_PARAM_INT32', 1, 'clothing_opened');

TwAddButton(mainBar, 'Fill Ammo', Weapon.item('FillWeapon'), NULL, 'group=Weapon ');

TwAddButton(mainBar, 'Unlimited Ammo', Weapon.item('TUClip'), NULL, 'group=Weapon ');

TwAddButton(mainBar, 'Give Weapons', Weapon.item('TGiveWeapons'), NULL, 'group=Weapon ');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarRW(mainBar, 'Explosive Melee', 'TW_TYPE_BOOLCPP', Weapon.item('explosivemelee'), 'group=Weapon');

TwAddVarRW(mainBar, 'Explosive Ammo', 'TW_TYPE_BOOLCPP', Weapon.item('explosiveammo'), 'group=Weapon');

TwAddVarRW(mainBar, 'Fire Ammo', 'TW_TYPE_BOOLCPP', Weapon.item('fireammo'), 'group=Weapon');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarCB(mainBar, 'Clip Size', 'TW_TYPE_INT32', Weapon.getter('SetClipSizeCallback'), Weapon.setter('GetClipSizeCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Accuracy Spread', 'TW_TYPE_FLOAT', Weapon.getter('SetAccuracySpreadCallback'), Weapon.setter('GetAccuracySpreadCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Accurate Mode Accuracy Modifier', 'TW_TYPE_FLOAT', Weapon.getter('SetAccurateModeAccuracyModifierCallback'), Weapon.setter('GetAccurateModeAccuracyModifierCallback'), wcb, 'group=Weapon');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarCB(mainBar, 'Run and Gun Accuracy Modifier', 'TW_TYPE_FLOAT', Weapon.getter('SetRunAndGunAccuracyModifierCallback'), Weapon.setter('GetRunAndGunAccuracyModifierCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Run and Gun Accuracy Min Override', 'TW_TYPE_FLOAT', Weapon.getter('SetRunAndGunAccuracyMinOverrideCallback'), Weapon.setter('GetRunAndGunAccuracyMinOverrideCallback'), wcb, 'group=Weapon');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarCB(mainBar, 'Recoil Accuracy Max', 'TW_TYPE_FLOAT', Weapon.getter('SetRecoilAccuracyMaxCallback'), Weapon.setter('GetRecoilAccuracyMaxCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Recoil Error Time', 'TW_TYPE_FLOAT', Weapon.getter('SetRecoilErrorTimeCallback'), Weapon.setter('GetRecoilErrorTimeCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Recoil Recovery Rate', 'TW_TYPE_FLOAT', Weapon.getter('SetRecoilRecoveryRateCallback'), Weapon.setter('GetRecoilRecoveryRateCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Recoil Accuracy To Allow HeadShot Distance Player', 'TW_TYPE_FLOAT', Weapon.getter('SetRecoilAccuracyToAllowHeadShotDistancePlayerCallback'), Weapon.setter('GetRecoilAccuracyToAllowHeadShotDistancePlayerCallback'), wcb, 'group=Weapon');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarCB(mainBar, 'Min HeadShot Distance Player', 'TW_TYPE_FLOAT', Weapon.getter('SetMinHeadShotDistancePlayerCallback'), Weapon.setter('GetMinHeadShotDistancePlayerCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Max HeadShot Distance Player', 'TW_TYPE_FLOAT', Weapon.getter('SetMaxHeadShotDistancePlayerCallback'), Weapon.setter('GetMaxHeadShotDistancePlayerCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'HeadShot Damage Modifier Player', 'TW_TYPE_FLOAT', Weapon.getter('SetHeadShotDamageModifierPlayerCallback'), Weapon.setter('GetHeadShotDamageModifierPlayerCallback'), wcb, 'group=Weapon');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarCB(mainBar, 'Damage', 'TW_TYPE_FLOAT', Weapon.getter('SetDamageCallback'), Weapon.setter('GetDamageCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force', 'TW_TYPE_FLOAT', Weapon.getter('SetForceCallback'), Weapon.setter('GetForceCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Hit Ped', 'TW_TYPE_FLOAT', Weapon.getter('SetForceHitPedCallback'), Weapon.setter('GetForceHitPedCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Hit Vehicle', 'TW_TYPE_FLOAT', Weapon.getter('SetForceHitVehicleCallback'), Weapon.setter('GetForceHitVehicleCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Hit Flying Heli', 'TW_TYPE_FLOAT', Weapon.getter('SetForceHitFlyingHeliCallback'), Weapon.setter('GetForceHitFlyingHeliCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Mass Strength Multi', 'TW_TYPE_FLOAT', Weapon.getter('SetForceMassStrengthMultCallback'), Weapon.setter('GetForceMassStrengthMultCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Falloff Range Start', 'TW_TYPE_FLOAT', Weapon.getter('SetForceFalloffRangeStartCallback'), Weapon.setter('GetForceFalloffRangeStartCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Falloff Range End', 'TW_TYPE_FLOAT', Weapon.getter('SetForceFalloffRangeEndCallback'), Weapon.setter('GetForceFalloffRangeEndCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Force Falloff Min', 'TW_TYPE_FLOAT', Weapon.getter('SetForceFalloffMinCallback'), Weapon.setter('GetForceFalloffMinCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Projectile Force', 'TW_TYPE_FLOAT', Weapon.getter('SetProjectileForceCallback'), Weapon.setter('GetProjectileForceCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Frag Impulse', 'TW_TYPE_FLOAT', Weapon.getter('SetFragImpulseCallback'), Weapon.setter('GetFragImpulseCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Penetration', 'TW_TYPE_FLOAT', Weapon.getter('SetPenetrationCallback'), Weapon.setter('GetPenetrationCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Bullets In Batch', 'TW_TYPE_INT32', Weapon.getter('SetBulletsInBatchCallback'), Weapon.setter('GetBulletsInBatchCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Batch Spread', 'TW_TYPE_FLOAT', Weapon.getter('SetBatchSpreadCallback'), Weapon.setter('GetBatchSpreadCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Time Between Shots', 'TW_TYPE_FLOAT', Weapon.getter('SetTimeBetweenShotsCallback'), Weapon.setter('GetTimeBetweenShotsCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Time Left Between Shots Cached Fired', 'TW_TYPE_FLOAT', Weapon.getter('SetTimeLeftBetweenShotsWhereShouldFireIsCachedCallback'), Weapon.setter('GetTimeLeftBetweenShotsWhereShouldFireIsCachedCallback'), wcb, 'group=Weapon');

TwAddSeparator(mainBar, NULL, ' group=\'Weapon\' ');

TwAddVarCB(mainBar, 'Tracer Fx Chance SP', 'TW_TYPE_FLOAT', Weapon.getter('SetTracerFxChanceSPCallback'), Weapon.setter('GetTracerFxChanceSPCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Tracer Fx Chance MP', 'TW_TYPE_FLOAT', Weapon.getter('SetTracerFxChanceMPCallback'), Weapon.setter('GetTracerFxChanceMPCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Flash Fx Chance SP', 'TW_TYPE_FLOAT', Weapon.getter('SetFlashFxChanceSPCallback'), Weapon.setter('GetFlashFxChanceSPCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Flash Fx Chance MP', 'TW_TYPE_FLOAT', Weapon.getter('SetFlashFxChanceMPCallback'), Weapon.setter('GetFlashFxChanceMPCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Flash Fx Scale', 'TW_TYPE_FLOAT', Weapon.getter('SetFlashFxScaleCallback'), Weapon.setter('GetFlashFxScaleCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Lock On Range', 'TW_TYPE_FLOAT', Weapon.getter('SetLockOnRangeCallback'), Weapon.setter('GetLockOnRangeCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Weapon Range', 'TW_TYPE_FLOAT', Weapon.getter('SetWeaponRangeCallback'), Weapon.setter('GetWeaponRangeCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Damage FallOff Range Min', 'TW_TYPE_FLOAT', Weapon.getter('SetDamageFallOffRangeMinCallback'), Weapon.setter('GetDamageFallOffRangeMinCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Damage FallOff Range Max', 'TW_TYPE_FLOAT', Weapon.getter('SetDamageFallOffRangeMaxCallback'), Weapon.setter('GetDamageFallOffRangeMaxCallback'), wcb, 'group=Weapon');

TwAddVarCB(mainBar, 'Damage FallOff Modifier', 'TW_TYPE_FLOAT', Weapon.getter('SetDamageFallOffModifierCallback'), Weapon.setter('GetDamageFallOffModifierCallback'), wcb, 'group=Weapon');

TwSetParam(mainBar, 'Weapon', 'opened', 'TW_PARAM_INT32', 1, 'weapon_opened');

TwAddButton(mainBar, 'Fix Vehicle', Vehicle.item('TFixVehicle'), NULL, 'group=Vehicle ');

TwAddVarCB(mainBar, 'Mod Index', 'TW_TYPE_INT32', Vehicle.getter('SetVehicleModIndexCallback'), Vehicle.setter('GetVehicleModIndexCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Mod Name', 'TW_TYPE_STDSTRING', Vehicle.getter('SetMyStdStringCB'), Vehicle.setter('GetMyStdStringCB'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Mod Selection', 'TW_TYPE_INT32', Vehicle.getter('SetVehicleModNumberCallback'), Vehicle.setter('GetVehicleModNumberCallback'), vcb, 'group=Vehicle');

TwAddButton(mainBar, 'Upgrade Vehicle', Vehicle.item('TMaxVehicle'), NULL, 'group=Vehicle ');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarCB(mainBar, 'Primary R', 'TW_TYPE_INT32', Vehicle.getter('SetVehicleRCallback'), Vehicle.setter('GetVehicleRCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Primary G', 'TW_TYPE_INT32', Vehicle.getter('SetVehicleGCallback'), Vehicle.setter('GetVehicleGCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Primary B', 'TW_TYPE_INT32', Vehicle.getter('SetVehicleBCallback'), Vehicle.setter('GetVehicleBCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Secondary R', 'TW_TYPE_INT32', Vehicle.getter('SetVehicle2RCallback'), Vehicle.setter('GetVehicle2RCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Secondary G', 'TW_TYPE_INT32', Vehicle.getter('SetVehicle2GCallback'), Vehicle.setter('GetVehicle2GCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Secondary B', 'TW_TYPE_INT32', Vehicle.getter('SetVehicle2BCallback'), Vehicle.setter('GetVehicle2BCallback'), vcb, 'group=Vehicle');

TwAddButton(mainBar, 'Paint Primary', Vehicle.item('TPaintVehicle'), NULL, 'group=Vehicle ');

TwAddButton(mainBar, 'Paint Secondary', Vehicle.item('TPaint2Vehicle'), NULL, 'group=Vehicle ');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarRW(mainBar, 'Vehicle Invincibility', 'TW_TYPE_BOOLCPP', Vehicle.item('vehgodmode'), 'group=Vehicle');

TwAddVarRW(mainBar, 'Bulletproof Tires', 'TW_TYPE_BOOLCPP', Vehicle.item('bptires'), 'group=Vehicle');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarCB(mainBar, 'Acceleration', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleSpeedCallback'), Vehicle.setter('GetVehicleSpeedCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Mass', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleMassCallback'), Vehicle.setter('GetVehicleMassCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Gravity', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleGravityCallback'), Vehicle.setter('GetVehicleGravityCallback'), vcb, 'group=Vehicle');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarCB(mainBar, 'Initial Drive Force', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleInitialDriveForceCallback'), Vehicle.setter('GetVehicleInitialDriveForceCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Steering Lock', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleSteringCallback'), Vehicle.setter('GetVehicleSteringCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Brake Force', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleBrakeForceCallback'), Vehicle.setter('GetVehicleBrakeForceCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Suspension Force', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleSuspensionForceCallback'), Vehicle.setter('GetVehicleSuspensionForceCallback'), vcb, 'group=Vehicle');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarCB(mainBar, 'Center of Mass X', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleCentreOfMassxCallback'), Vehicle.setter('GetVehicleCentreOfMassxCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Center of Mass Y', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleCentreOfMassyCallback'), Vehicle.setter('GetVehicleCentreOfMassyCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Center of Mass Z', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleCentreOfMasszCallback'), Vehicle.setter('GetVehicleCentreOfMasszCallback'), vcb, 'group=Vehicle');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarCB(mainBar, 'Inertia Multiplier X', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleInertiaMultiplierxCallback'), Vehicle.setter('GetVehicleInertiaMultiplierxCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Inertia Multiplier Y', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleInertiaMultiplieryCallback'), Vehicle.setter('GetVehicleInertiaMultiplieryCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Inertia Multiplier Z', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleInertiaMultiplierzCallback'), Vehicle.setter('GetVehicleInertiaMultiplierzCallback'), vcb, 'group=Vehicle');

TwAddSeparator(mainBar, NULL, ' group=\'Vehicle\' ');

TwAddVarCB(mainBar, 'Up Shift', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleUpShiftCallback'), Vehicle.setter('GetVehicleUpShiftCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Down Shift', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleDownShiftCallback'), Vehicle.setter('GetVehicleDownShiftCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Corner Grip', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleCornerGripCallback'), Vehicle.setter('GetVehicleCornerGripCallback'), vcb, 'group=Vehicle');

TwAddVarCB(mainBar, 'Line Grip', 'TW_TYPE_FLOAT', Vehicle.getter('SetVehicleLineGripCallback'), Vehicle.setter('GetVehicleLineGripCallback'), vcb, 'group=Vehicle');

TwSetParam(mainBar, 'Vehicle', 'opened', 'TW_PARAM_INT32', 1, 'vehicle_opened');

TwAddButton(mainBar, 'Teleport to Waypoint', Teleport.item('Waypoint'), NULL, 'group=Teleport help=\'In GTA: V, this will attempt to teleport you to the waypoint set on your map. You must set a waypoint first, BEFORE using this feature.\'');

TwAddSeparator(mainBar, NULL, ' group=\'Teleport\' ');

TwAddButton(mainBar, 'Teleport to Custom Location 1', Teleport.item('TLoadCustomTP1'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Custom Location 2', Teleport.item('TLoadCustomTP2'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Custom Location 3', Teleport.item('TLoadCustomTP3'), NULL, 'group=Teleport');

TwAddSeparator(mainBar, NULL, ' group=\'Teleport\' ');

TwAddButton(mainBar, 'Teleport to LSC', Teleport.item('LSC'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Maze', Teleport.item('Maze'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Chiliad', Teleport.item('Chiliad'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Zancudo', Teleport.item('Zancudo'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to MaskShop', Teleport.item('MaskShop'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Ponsonbys', Teleport.item('Ponsonbys'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Ammunation', Teleport.item('Ammunation'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Airport', Teleport.item('Airport'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Waterfall', Teleport.item('Waterfall'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to FIB', Teleport.item('FIB'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Humane Labs 1', Teleport.item('HumaneLabs1'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Humane Labs 2', Teleport.item('HumaneLabs2'), NULL, 'group=Teleport');

TwAddButton(mainBar, 'Teleport to Zancudo Tower', Teleport.item('ZancudoTower'), NULL, 'group=Teleport');

TwSetParam(mainBar, 'Teleport', 'opened', 'TW_PARAM_INT32', 1, 'teleport_opened');

TwAddButton(mainBar, 'Save Custom Location 1', Teleport.item('TSaveCustomTP1'), NULL, 'group=\'Menu Settings\'');

TwAddButton(mainBar, 'Save Custom Location 2', Teleport.item('TSaveCustomTP2'), NULL, 'group=\'Menu Settings\'');

TwAddButton(mainBar, 'Save Custom Location 3', Teleport.item('TSaveCustomTP3'), NULL, 'group=\'Menu Settings\'');

TwAddVarRW(mainBar, 'Disable Controls', 'TW_TYPE_BOOLCPP', Player.item('disablecontrol'), 'group=\'Menu Settings\'');
